import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'

export default function Layout({ children }) {
  return (
    <>
    <Head>
        <title>Flyplassreklame - Haugesund lufthavn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
    </Head>
    <Navbar />
        <main>{children}</main>
    <Footer />
    </>
  )
}